OBJS = ast.cmo parser.cmo scanner.cmo bytecode.cmo compile.cmo cb.cmo

cb : $(OBJS)
	ocamlc -o cb $(OBJS)

scanner.ml : scanner.mll
	ocamllex scanner.mll

parser.ml parser.mli : parser.mly
	ocamlyacc parser.mly

%.cmo : %.ml
	ocamlc -c $<

%.cmi : %.mli
	ocamlc -c $<

cb.tar.gz : $(TARFILES)
	cd .. && tar czf cb/cb.tar.gz $(TARFILES:%=cb/%)

.PHONY : clean
clean :
	rm -f *~ cb parser.ml parser.mli scanner.ml testall.log \
	*.cmo *.cmi *.out *.diff

.PHONY : all
all : clean cb

# Generated by ocamldep *.ml *.mli
ast.cmo: 
ast.cmx: 
bytecode.cmo: ast.cmo 
bytecode.cmx: ast.cmx 
compile.cmo: bytecode.cmo ast.cmo 
compile.cmx: bytecode.cmx ast.cmx
cb.cmo: scanner.cmo parser.cmi compile.cmo \
    bytecode.cmo ast.cmo 
cb.cmx: scanner.cmx parser.cmx compile.cmx \
    bytecode.cmx ast.cmx 
parser.cmo: ast.cmo parser.cmi 
parser.cmx: ast.cmx parser.cmi 
scanner.cmo: parser.cmi 
scanner.cmx: parser.cmx 
parser.cmi: ast.cmo 
