OBJS = parser.cmo
#OBJS = scanner.cmo ast.cmo parser.cmo intrepret.cmo cb.cmo

#cb : $(OBJS)
#	ocamlc -o cb $(OBJS)

#scanner.ml : scanner.mll
#	ocamllex scanner.mll

parser.ml parser.mli : parser.mly
	ocamlyacc parser.mly

#%.cmo : %.ml
	ocamlc -c $<

#%.cmi : %.mli
	ocamlc -c $<

#TARFILES = Makefile parser.mly

#cb.tar.gz : $(TARFILES)
#	cd .. && tar zcf src/cb.tar.gz $(TARFILES:%=cb/%)

.PHONY : clean
clean :
	rm -rf *.cmo *.cmi cb parser.mli parser.ml scanner.ml

# generated by ocamldep *.ml *.mli
#ast.cmo:
#ast.cmx:
#interpret.cmo: ast.cmo
#interpret.cmx: ast.cmx
#cb.cmo: scanner.cmo parser.cmi interpret.cmo \
#    ast.cmo 
#cb.cmx: scanner.cmx parser.cmx interpret.cmx \
#    ast.cmx     
#parser.cmo: ast.cmo parser.cmi 
#parser.cmx: ast.cmx parser.cmi 
#scanner.cmo: parser.cmi 
#scanner.cmx: parser.cmx 
#parser.cmi: ast.cmo 